name: kiddos
region: nyc

services:
  - name: backend
    source_dir: backend
    github:
      repo: codegirl-007/kiddos
      branch: master
      deploy_on_push: true

    build_command: npm install && npm run build
    run_command: npm start

    environment_slug: node-js
    instance_size_slug: basic-xxs
    instance_count: 1
    http_port: 3000

    routes:
      - path: /api

    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: TURSO_URL
        value: ${TURSO_URL}
        type: SECRET
      - key: TURSO_AUTH_TOKEN
        value: ${TURSO_AUTH_TOKEN}
        type: SECRET
      - key: YOUTUBE_API_KEY
        value: ${YOUTUBE_API_KEY}
        type: SECRET
      - key: JWT_SECRET
        value: ${JWT_SECRET}
        type: SECRET
      - key: JWT_REFRESH_SECRET
        value: ${JWT_REFRESH_SECRET}
        type: SECRET
      - key: INITIAL_ADMIN_USERNAME
        value: ${INITIAL_ADMIN_USERNAME}
      - key: INITIAL_ADMIN_PASSWORD
        value: ${INITIAL_ADMIN_PASSWORD}
        type: SECRET
      - key: CORS_ORIGIN
        value: ${frontend.PUBLIC_URL}

    health_check:
      http_path: /api/health

static_sites:
  - name: frontend
    source_dir: frontend
    github:
      repo: codegirl-007/kiddos
      branch: master
      deploy_on_push: true

    build_command: npm install && npm run build
    output_dir: dist
    catchall_document: index.html

    routes:
      - path: /

    envs:
      - key: VITE_API_URL
        value: ${backend.PUBLIC_URL}/api