domains:
- domain: rainbowscupcakesandunicorns.com
  type: PRIMARY
  zone: rainbowscupcakesandunicorns.com
- domain: www.rainbowscupcakesandunicorns.com
  type: ALIAS
  zone: rainbowscupcakesandunicorns.com
ingress:
  rules:
  - component:
      name: backend
    match:
      path:
        prefix: /api
  - component:
      name: frontend
    match:
      path:
        prefix: /
name: kiddos
region: nyc
services:
- build_command: npm install && npm run build
  environment_slug: node-js
  envs:
  - key: TURSO_URL
    scope: RUN_AND_BUILD_TIME
    value: libsql://kiddos-db-stephanie-gredell.aws-us-west-2.turso.io
  - key: TURSO_AUTH_TOKEN
    scope: RUN_AND_BUILD_TIME
    value: eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NjQyNjg4NTcsImlkIjoiNzM5M2JhNTYtZWE3Ni00NTMwLWE3NDktNmVjNDhiOGIyODZhIiwicmlkIjoiNGE2ZWRlZTgtYjU2Yy00ZDc4LTk5MzgtZTBkMjExYjNkMjIzIn0.69PsVp6-CE7k2zKe_tpwpfOiWph4vNY6-ZcE2x3OP3n4RiZeHP1C-aVNdo2tZ8t5WvaT0z2HUGrKgO8X50f5Bg
  - key: YOUTUBE_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: AIzaSyA06ccav0VA4ItxWIx6eG4C0REezbKOS7M
  - key: JWT_SECRET
    scope: RUN_AND_BUILD_TIME
    value: your-secret-key-min-32-chars
  - key: JWT_REFRESH_SECRET
    scope: RUN_AND_BUILD_TIME
    value: your-refresh-secret-different-from-above
  - key: PORT
    scope: RUN_AND_BUILD_TIME
    value: "8080"
  - key: CORS_ORIGIN
    scope: RUN_AND_BUILD_TIME
    value: https://www.rainbowscupcakesandunicorns.com
  - key: NODE_ENV
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: ACCESS_TOKEN_EXPIRY
    scope: RUN_AND_BUILD_TIME
    value: 15m
  - key: REFRESH_TOKEN_EXPIRY
    scope: RUN_AND_BUILD_TIME
    value: 7d
  - key: INITIAL_ADMIN_USERNAME
    scope: RUN_AND_BUILD_TIME
    value: admin
  - key: INITIAL_ADMIN_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: change-this-secure-password
  github:
    branch: master
    deploy_on_push: true
    repo: codegirl-007/kiddos
  health_check:
    http_path: /api/health
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: backend
  run_command: npm start
  source_dir: backend
static_sites:
- build_command: npm install && npm run build
  catchall_document: index.html
  envs:
  - key: VITE_API_URL
    scope: BUILD_TIME
    value: https://www.rainbowscupcakesandunicorns.com/api
  github:
    branch: master
    deploy_on_push: true
    repo: codegirl-007/kiddos
  name: frontend
  output_dir: dist
  source_dir: frontend
